Create an RDD named `products` with `parallelize` containing the elements in the output.

In [28]:
products = sc.parallelize(['Apple', 'Apple', 'Cheese', 'Apple', 'Orange'])
products.collect()

['Apple', 'Apple', 'Cheese', 'Apple', 'Orange']

Count the number of elements in `products`

In [29]:
products.count()

5

Count the number of apples in `products`. Tip: use filter.

In [30]:
products.filter(lambda x: x == 'Apple').count()

3

show the (distinct) products.

In [31]:
products.distinct().collect()

['Apple', 'Orange', 'Cheese']

Download the file babynames from https://health.data.ny.gov/api/views/jxy9-yhdk/rows.csv?accessType=DOWNLOAD, store the file locally and load its contents into a RDD called `babynames` with textFile. Show the first 5 lines.

In [32]:
babynames = sc.textFile('../rows.csv')
babynames.take(5)

['Year,First Name,County,Sex,Count',
 '2013,GAVIN,ST LAWRENCE,M,9',
 '2013,LEVI,ST LAWRENCE,M,9',
 '2013,LOGAN,NEW YORK,M,44',
 '2013,HUDSON,NEW YORK,M,49']

The first line in the file is a header, filter out the first line to keep only lines with actual data.

In [33]:
firstline = babynames.first()
test = babynames.filter(lambda x: x != firstline)
test.take(5)

['2013,GAVIN,ST LAWRENCE,M,9',
 '2013,LEVI,ST LAWRENCE,M,9',
 '2013,LOGAN,NEW YORK,M,44',
 '2013,HUDSON,NEW YORK,M,49',
 '2013,GABRIEL,NEW YORK,M,50']

The elements in this RDD are each a line of text. Transform each element into a tuple or list that consists of the 5 columns in the csv by splitting the lines on comma characters. Show the first 5. Tip: you need `map` and the `split` method on Python Strings.

In [34]:
splitb = test.map(lambda x: x.split(','))
splitb.take(5)

[['2013', 'GAVIN', 'ST LAWRENCE', 'M', '9'],
 ['2013', 'LEVI', 'ST LAWRENCE', 'M', '9'],
 ['2013', 'LOGAN', 'NEW YORK', 'M', '44'],
 ['2013', 'HUDSON', 'NEW YORK', 'M', '49'],
 ['2013', 'GABRIEL', 'NEW YORK', 'M', '50']]

Count how many male babies are in the RDD.

In [35]:
males = splitb.filter(lambda x: x[3] == 'M')
males = males.map(lambda x: (x[3], x[4]))
males.reduceByKey(lambda x, y: int(x) + int(y)).take(5)

[('M', 667585)]

The next objective is to find the most given babyname.

First, convert the RDD into a key,value structure. Since we do not need anything but the name, we can convert every element into (name, 1). Show the first 5.

In [36]:
kv = splitb.map(lambda x: (x[1], x[4]))
kv = kv.reduceByKey(lambda x, y: int(x) + int(y))

Now you can aggregate the elements that have the same key, and sum the values to get the number of occurrences per name. Show the first 5, these might be different ones than displayed below. Tip: use `reduceByKey`

In [37]:
kv = kv.reduceByKey(lambda x, y: int(x) + int(y))
kv.take(1000)

[('GAVIN', 3618),
 ('LEVI', 1218),
 ('LOGAN', 6118),
 ('HUDSON', 873),
 ('GABRIEL', 5393),
 ('ELIZA', 341),
 ('MADELEINE', 459),
 ('ZARA', 329),
 ('DAISY', 412),
 ('JONATHAN', 5511),
 ('JACKSON', 3836),
 ('JUDY', 91),
 ('DAVID', 8585),
 ('SEBASTIAN', 4027),
 ('SAMUEL', 5358),
 ('DEVORA', 194),
 ('JAYDEN', 10770),
 ('MICHAEL', 12749),
 ('MATTHEW', 11161),
 ('CHARLES', 3054),
 ('LUNA', 511),
 ('ADELE', 143),
 ('LIAM', 7683),
 ('DYLAN', 7664),
 ('DANIEL', 10353),
 ('RYAN', 9978),
 ('ETHAN', 10524),
 ('WYATT', 1288),
 ('SURI', 159),
 ('ZISSY', 246),
 ('YIDES', 270),
 ('WILLIAM', 6935),
 ('ALEXANDER', 9401),
 ('LENA', 353),
 ('CORA', 267),
 ('GIA', 485),
 ('MADELINE', 1673),
 ('ANDREA', 980),
 ('TRINITY', 444),
 ('LEILANI', 429),
 ('HARMONY', 158),
 ('AMANDA', 1194),
 ('RACHEL', 3195),
 ('MARGOT', 88),
 ('NOA', 270),
 ('JESSICA', 1629),
 ('ABBY', 150),
 ('JENNY', 288),
 ('MILANA', 71),
 ('ADDISON', 1890),
 ('MACKENZIE', 1318),
 ('ADRIANNA', 1000),
 ('ATHENA', 309),
 ('HANNA', 221),
 ('ANIYAH', 491),
 ('CRYSTAL', 369),
 ('JULIET', 633),
 ('VALERIE', 928),
 ('ELOISE', 244),
 ('AMY', 1499),
 ('JOYCE', 297),
 ('SIMONE', 172),
 ('LIV', 69),
 ('HELENA', 101),
 ('ANDREW', 6696),
 ('SASHA', 414),
 ('IRIS', 372),
 ('LYLA', 485),
 ('CHASE', 2654),
 ('BRAYDEN', 2055),
 ('LINCOLN', 370),
 ('LEILA', 710),
 ('NICOLE', 2272),
 ('DAPHNE', 129),
 ('ROSE', 584),
 ('JOSEPHINE', 668),
 ('JADE', 1134),
 ('JASMINE', 1599),
 ('KAYLEE', 2065),
 ('AUBREY', 1357),
 ('BRIANNA', 3562),
 ('AMBER', 667),
 ('LIA', 653),
 ('GENESIS', 1888),
 ('SKYLAH', 61),
 ('HADASSAH', 125),
 ('SHIFRA', 126),
 ('SIENNA', 919),
 ('EMELY', 846),
 ('ALIYAH', 572),
 ('GISELLE', 661),
 ('CAMILLE', 146),
 ('VALERIA', 560),
 ('KAYLIN', 100),
 ('HEAVEN', 357),
 ('JAYLEEN', 320),
 ('ELAINE', 187),
 ('AHUVA', 141),
 ('RENEE', 57),
 ('SHIRA', 228),
 ('ALISA', 81),
 ('ELISHEVA', 92),
 ('FRADEL', 108),
 ('EMMA', 9735),
 ('KAYLA', 3565),
 ('EMILIA', 712),
 ('GABRIELLA', 4554),
 ('LILA', 753),
 ('ARYA', 219),
 ('HANNAH', 3187),
 ('AISHA', 334),
 ('PAISLEY', 112),
 ('YARETZI', 142),
 ('SARAI', 316),
 ('NYLA', 517),
 ('FIONA', 1019),
 ('ISABELLE', 1148),
 ('SKYLA', 288),
 ('ALIZA', 218),
 ('KYLIE', 1463),
 ('NICHOLAS', 7945),
 ('ANTHONY', 10071),
 ('YAEL', 148),
 ('CLAIRE', 1466),
 ('LAYLA', 2007),
 ('SHERLYN', 85),
 ('ERICA', 280),
 ('NATHALY', 85),
 ('KYLEIGH', 38),
 ('LILIANNA', 68),
 ('NANCY', 97),
 ('LESLY', 85),
 ('ROIZA', 26),
 ('MIRI', 65),
 ('IDY', 59),
 ('MUSHKA', 33),
 ('BLAKE', 1506),
 ('ELEANOR', 687),
 ('NORA', 894),
 ('AUDREY', 1204),
 ('VALENTINA', 1755),
 ('ARIANA', 2327),
 ('KRISTEN', 86),
 ('ERIN', 599),
 ('ISABEL', 1125),
 ('ASHLEY', 4157),
 ('VIVIENNE', 304),
 ('LUCY', 1040),
 ('NAOMI', 1416),
 ('ALEXA', 2658),
 ('CAROLINE', 1123),
 ('VIVIAN', 985),
 ('HAILEY', 3301),
 ('MIRANDA', 191),
 ('JAXON', 709),
 ('OLIVE', 95),
 ('CYNTHIA', 224),
 ('MELANY', 236),
 ('MILA', 813),
 ('KATHERINE', 2086),
 ('CAMILA', 1953),
 ('BELLA', 1337),
 ('ANABELLE', 50),
 ('EVE', 149),
 ('CHRISTINE', 157),
 ('SAMANTHA', 4575),
 ('ANNA', 2665),
 ('EVA', 1711),
 ('FRANCES', 83),
 ('FARAH', 35),
 ('JANIYAH', 118),
 ('ELINA', 83),
 ('SIMA', 187),
 ('LIBA', 145),
 ('MOSHE', 2557),
 ('EVELYN', 2142),
 ('SOPHIA', 10994),
 ('PENELOPE', 1103),
 ('EMILY', 8074),
 ('ALEXANDRA', 2669),
 ('MADISON', 7509),
 ('CHLOE', 4996),
 ('ABRAHAM', 2044),
 ('ISAAC', 3267),
 ('ELIJAH', 4928),
 ('AARON', 4034),
 ('MIA', 7297),
 ('ISABELLA', 11278),
 ('MARCELLO', 41),
 ('ADAM', 3353),
 ('FRANCESCO', 102),
 ('RONALD', 221),
 ('TYLER', 5277),
 ('DERRICK', 113),
 ('SANTINO', 133),
 ('EMANUEL', 505),
 ('BROOKLYNN', 67),
 ('JOSIAH', 2170),
 ('ERIC', 2525),
 ('JAYLEN', 470),
 ('ABEL', 176),
 ('CODY', 269),
 ('AHMED', 417),
 ('RAFAEL', 728),
 ('MENACHEM', 861),
 ('ARON', 765),
 ('YITZCHOK', 679),
 ('SHLOMO', 631),
 ('GERARD', 29),
 ('AARAV', 42),
 ('LUCIANO', 107),
 ('FREDERICK', 91),
 ('DONOVAN', 250),
 ('DENNIS', 277),
 ('KIERAN', 232),
 ('NICO', 199),
 ('SANTIAGO', 514),
 ('SKYE', 156),
 ('AUSTIN', 2339),
 ('PHILIP', 354),
 ('NATHANIEL', 2662),
 ('YEHUDA', 846),
 ('ISAIAH', 2746),
 ('EMMETT', 229),
 ('DAMIEN', 377),
 ('NIA', 399),
 ('GIANNA', 3895),
 ('JUAN', 1201),
 ('MICAH', 630),
 ('OSCAR', 1183),
 ('GIANLUCA', 97),
 ('NIKO', 51),
 ('CHRISTINA', 794),
 ('CALEB', 2943),
 ('MARIO', 373),
 ('JOHAN', 347),
 ('GREGORY', 435),
 ('JAMESON', 337),
 ('SAWYER', 253),
 ('ANGELA', 970),
 ('ARIEL', 1219),
 ('LUCIANA', 128),
 ('XAVIER', 2714),
 ('IVAN', 1249),
 ('LOUIS', 661),
 ('KENNETH', 981),
 ('OMAR', 1131),
 ('KING', 441),
 ('KYLE', 2187),
 ('JOSE', 2078),
 ('REID', 98),
 ('ROCCO', 246),
 ('SALVATORE', 457),
 ('TREVOR', 353),
 ('JESSE', 522),
 ('BRADY', 705),
 ('EMMANUEL', 1432),
 ('CHRIS', 496),
 ('SPENCER', 407),
 ('EDWIN', 1015),
 ('DEAN', 551),
 ('CARLOS', 1642),
 ('ALEJANDRO', 901),
 ('JOEL', 1964),
 ('KAIDEN', 689),
 ('ELIEZER', 416),
 ('TZVI', 481),
 ('ZACHARY', 3400),
 ('RICHARD', 1658),
 ('TRISTAN', 1929),
 ('MARCUS', 1171),
 ('SHULEM', 427),
 ('JAKE', 2608),
 ('LUCA', 1604),
 ('MILES', 987),
 ('VICTOR', 1321),
 ('ANGELINA', 2767),
 ('TIMOTHY', 1287),
 ('MARCO', 591),
 ('LORENZO', 604),
 ('FELIX', 555),
 ('KADEN', 394),
 ('LUIS', 2059),
 ('NICOLAS', 1281),
 ('SHANE', 820),
 ('FRANK', 751),
 ('JOSUE', 604),
 ('DOMINICK', 738),
 ('PAUL', 1053),
 ('BRYCE', 955),
 ('MATTEO', 592),
 ('GEORGE', 1415),
 ('GRAYSON', 728),
 ('SEAN', 2577),
 ('ELIAS', 1313),
 ('LEONARDO', 1076),
 ('MOHAMMED', 534),
 ('SAM', 316),
 ('HERSHY', 267),
 ('ELLIOT', 399),
 ('LEON', 380),
 ('JAX', 128),
 ('RORY', 107),
 ('BRODY', 889),
 ('ANGELO', 647),
 ('COLE', 1330),
 ('BRENDAN', 753),
 ('NAFTALI', 209),
 ('MALACHI', 801),
 ('AMARI', 480),
 ('ALVIN', 396),
 ('MILO', 273),
 ('DOV', 329),
 ('DOMINIC', 2261),
 ('ERICK', 923),
 ('MESSIAH', 334),
 ('AUGUST', 298),
 ('JULIANNA', 1249),
 ('KENZIE', 50),
 ('CALLIE', 143),
 ('HAYLEE', 83),
 ('LILAH', 152),
 ('HOPE', 157),
 ('DANNY', 484),
 ('AILEEN', 123),
 ('LAWRENCE', 157),
 ('BENZION', 109),
 ('ROMAN', 507),
 ('JESUS', 855),
 ('SAMIR', 143),
 ('HAYDEN', 698),
 ('JENNA', 754),
 ('CHARLIE', 395),
 ('NOEL', 293),
 ('ELIYAHU', 251),
 ('JAIDEN', 889),
 ('CALVIN', 280),
 ('WILSON', 238),
 ('JULIANNE', 40),
 ('CHARLEY', 31),
 ('ALYSSA', 2662),
 ('YEHOSHUA', 205),
 ('HAYLEY', 134),
 ('ALLIE', 52),
 ('CARLY', 206),
 ('EVANGELINE', 209),
 ('ANA', 469),
 ('CASSIDY', 261),
 ('BIANCA', 593),
 ('ALINA', 672),
 ('MELODY', 444),
 ('EDEN', 391),
 ('NEVAEH', 1470),
 ('KYLEE', 86),
 ('LILLIANA', 209),
 ('LEXI', 82),
 ('STANLEY', 159),
 ('SHLOME', 146),
 ('ADEN', 267),
 ('JAVIER', 543),
 ('RANDY', 452),
 ('MALIK', 327),
 ('EFRAIM', 173),
 ('KATE', 653),
 ('MAEVE', 322),
 ('MYRA', 29),
 ('SIENA', 183),
 ('KIMBERLY', 1630),
 ('DANIELLA', 923),
 ('CAMRYN', 207),
 ('HERSH', 163),
 ('MEILECH', 50),
 ('JAYCE', 421),
 ('HALEY', 387),
 ('KATIE', 555),
 ('BAILEY', 242),
 ('ARIELLE', 398),
 ('CAIDEN', 180),
 ('CHANCE', 163),
 ('ALLEN', 399),
 ('JOHNNY', 295),
 ('NELSON', 240),
 ('LILLY', 383),
 ('FATIMA', 686),
 ('JORDYN', 504),
 ('GIOVANNA', 160),
 ('KYLA', 199),
 ('KARA', 125),
 ('KATHRYN', 187),
 ('ANGIE', 431),
 ('WESLEY', 408),
 ('JENNIFER', 1286),
 ('MAKAYLA', 1430),
 ('JAYCEON', 158),
 ('MALCOLM', 83),
 ('HAMZA', 172),
 ('MELISSA', 773),
 ('ZAINAB', 162),
 ('PIPER', 292),
 ('AHARON', 128),
 ('MOISHE', 170),
 ('MEYER', 28),
 ('AMAYA', 696),
 ('REAGAN', 301),
 ('SERENA', 343),
 ('LIANA', 313),
 ('REESE', 367),
 ('STEPHANIE', 1265),
 ('FINN', 320),
 ('JUSTICE', 130),
 ('KENNEDY', 501),
 ('MYA', 1066),
 ('ESTHER', 2746),
 ('RAPHAEL', 245),
 ('TONY', 143),
 ('LUCIEN', 31),
 ('THEO', 125),
 ('NAFTULI', 138),
 ('BENSON', 123),
 ('PINCHAS', 149),
 ('SHLOIME', 93),
 ('GIAVANNA', 213),
 ('CHESKY', 53),
 ('LEA', 241),
 ('CADEN', 371),
 ('FERNANDO', 333),
 ('MICHAELA', 237),
 ('MEGAN', 746),
 ('BRYNN', 225),
 ('JULIEN', 118),
 ('ALEC', 64),
 ('KAREEM', 151),
 ('AHMAD', 113),
 ('ELVIS', 72),
 ('NACHMAN', 101),
 ('TERRENCE', 140),
 ('DIANA', 986),
 ('GABRIELLE', 1274),
 ('LAILA', 1155),
 ('VANESSA', 1109),
 ('ALESSANDRA', 311),
 ('FAITH', 1046),
 ('SIERRA', 140),
 ('DESTINY', 1021),
 ('DELANEY', 221),
 ('EMERSON', 284),
 ('ALYSON', 40),
 ('LONDYN', 177),
 ('KEEGAN', 144),
 ('JADIEL', 360),
 ('NORAH', 177),
 ('COLLIN', 381),
 ('KALEB', 326),
 ('JOURNEY', 53),
 ('IZABELLA', 276),
 ('CAMDEN', 316),
 ('ADELINE', 166),
 ('GIANNI', 209),
 ('BENTLEY', 307),
 ('MIRACLE', 102),
 ('JORDY', 27),
 ('DANICA', 53),
 ('TRANY', 112),
 ('RAIZY', 638),
 ('BATSHEVA', 221),
 ('CHAVA', 393),
 ('LENNY', 34),
 ('DILAN', 37),
 ('YOUSSEF', 61),
 ('JAYSON', 421),
 ('TRAVIS', 343),
 ('BRUCHA', 109),
 ('RIVKA', 1254),
 ('MALKA', 776),
 ('MATHEW', 245),
 ('ROY', 117),
 ('DAMON', 77),
 ('RIVKY', 540),
 ('SHAINDY', 575),
 ('ZAIN', 107),
 ('ORION', 67),
 ('ANDRES', 393),
 ('AMINATA', 166),
 ('PESSY', 332),
 ('ESTY', 198),
 ('MATIAS', 140),
 ('BAILA', 576),
 ('DINA', 429),
 ('FAIGA', 216),
 ('JALIYAH', 55),
 ('TENZIN', 424),
 ('GOLDY', 316),
 ('BRACHA', 243),
 ('JAYLAH', 69),
 ('EMILIO', 91),
 ('LIBBY', 238),
 ('YOCHEVED', 236),
 ('ROSA', 91),
 ('PEREL', 102),
 ('MAMADOU', 193),
 ('HECTOR', 308),
 ('CESAR', 411),
 ('SHARON', 198),
 ('CATALINA', 92),
 ('MELINA', 178),
 ('LINA', 93),
 ('EZEKIEL', 137),
 ('JARIEL', 124),
 ('ADRIEL', 174),
 ('URIEL', 65),
 ('AMADOU', 61),
 ('BRYANNA', 124),
 ('JADA', 918),
 ('CRISTOFER', 9),
 ('BRANDEN', 23),
 ('GINO', 36),
 ('TIFFANY', 803),
 ('MARYAM', 240),
 ('KEITH', 164),
 ('LUKA', 131),
 ('MARCOS', 186),
 ('TROY', 183),
 ('DREW', 252),
 ('MIKAEL', 19),
 ('CONOR', 180),
 ('ISSAC', 89),
 ('GRANT', 280),
 ('CHESKEL', 107),
 ('ESTER', 37),
 ('SURY', 264),
 ('MARIANA', 197),
 ('ARABELLA', 121),
 ('ALANNA', 75),
 ('MAKENZIE', 110),
 ('RAEGAN', 59),
 ('RYLIE', 46),
 ('WESTON', 97),
 ('GRIFFIN', 379),
 ('ELLIOTT', 212),
 ('LYRIC', 75),
 ('SETH', 192),
 ('BRENNAN', 127),
 ('ERIK', 330),
 ('JOHNATHAN', 289),
 ('BENNETT', 173),
 ('HARRY', 197),
 ('AMIRA', 257),
 ('SHAINA', 101),
 ('SHERRY', 29),
 ('AMELIE', 63),
 ('KELSEY', 217),
 ('DEBORAH', 103),
 ('JAZMINE', 97),
 ('KAYLIE', 93),
 ('APRIL', 88),
 ('RAQUEL', 118),
 ('SHOSHANA', 138),
 ('YITTA', 36),
 ('LITZY', 36),
 ('JOSELYN', 169),
 ('SANAI', 87),
 ('SANIYAH', 57),
 ('TAMIA', 101),
 ('SONIA', 103),
 ('QUEENIE', 56),
 ('CAROLINA', 89),
 ('ANGELIQUE', 123),
 ('NATHALIE', 122),
 ('KELVIN', 298),
 ('YADIEL', 78),
 ('EPHRAIM', 52),
 ('YITZCHAK', 71),
 ('SHLOIMY', 73),
 ('YECHEZKEL', 38),
 ('ANGUS', 26),
 ('ZALMEN', 87),
 ('MARVIN', 206),
 ('CYRUS', 60),
 ('KHALIL', 107),
 ('EDISON', 122),
 ('FABIAN', 64),
 ('MAURICE', 78),
 ('EITAN', 70),
 ('ALSTON', 28),
 ('YONA', 22),
 ('LEANDRO', 60),
 ('ZAYDEN', 108),
 ('ELIAN', 74),
 ('RUBEN', 84),
 ('JERMAINE', 68),
 ('MIKE', 75),
 ('SAMIYAH', 32),
 ('MARIANNA', 34),
 ('MAIYA', 18),
 ('JAMISON', 26),
 ('ENOS', 14),
 ('ADALYNN', 77),
 ('DILLON', 135),
 ('TYRONE', 25),
 ('SAVANNA', 94),
 ('MEGHAN', 184),
 ('JAYLENE', 185),
 ('JOHANNA', 90),
 ('LILIAN', 46),
 ('MARISA', 32),
 ('KIRA', 113),
 ('VIVIANA', 79),
 ('ANTONIA', 69),
 ('CLARE', 58),
 ('SARINA', 29),
 ('LEENA', 17),
 ('MELVIN', 100),
 ('JAIME', 70),
 ('NEIL', 50),
 ('GIANCARLO', 63),
 ('INES', 37),
 ('ISREAL', 19),
 ('BASYA', 26),
 ('DAYANA', 165),
 ('MARISSA', 219),
 ('ASHLYN', 98),
 ('KRISTINA', 63),
 ('LIVIA', 63),
 ('KRYSTAL', 31),
 ('LIANNA', 50),
 ('JIANNA', 25),
 ('JENCARLOS', 13),
 ('CRISTOPHER', 93),
 ('BRADEN', 70),
 ('FRANKLIN', 80),
 ('KRISTOPHER', 38),
 ('KELLAN', 66),
 ('ALLYSON', 126),
 ('YACHET', 39),
 ('ZARIA', 29),
 ('ZOIE', 18),
 ('ABDIEL', 32),
 ('DASHIELL', 46),
 ('AMARA', 71),
 ('DERICK', 17),
 ('DEVON', 130),
 ('ENRIQUE', 75),
 ('ERIKA', 189),
 ('FRANKIE', 47),
 ('GARY', 96),
 ('GWENDOLYN', 46),
 ('HADASSA', 24),
 ('JACKY', 51),
 ('JAELYNN', 37),
 ('ASHLEIGH', 16),
 ('JANIYA', 84),
 ('AUDRINA', 17),
 ('JESSIE', 93),
 ('JONAS', 85),
 ('AVI', 53),
 ('AVIANNA', 39),
 ('ALEJANDRA', 99),
 ('KAELYN', 82),
 ('KAILYN', 33),
 ('KALIYAH', 51),
 ('KAMERON', 78),
 ('KATERINA', 50),
 ('KIERA', 142),
 ('KRISTIAN', 68),
 ('KYRA', 82),
 ('LARA', 69),
 ('BRAEDEN', 45),
 ('LEELA', 40),
 ('LEORA', 36),
 ('LEYLA', 46),
 ('LUZ', 27),
 ('MAKENNA', 77),
 ('MARA', 39),
 ('BRYANT', 146),
 ('MAUREEN', 11),
 ('MILANI', 64),
 ('MIRA', 61),
 ('MONICA', 70),
 ('NATALY', 41),
 ('NICKOLAS', 48),
 ('PAITYN', 26),
 ('RICKY', 101),
 ('RIFKA', 39),
 ('RIHANNA', 172),
 ('RODNEY', 29),
 ('ROHAN', 104),
 ('SAUL', 100),
 ('SHAUN', 53),
 ('SHILOH', 98),
 ('SOLEIL', 20),
 ('TRENTON', 80),
 ('TZIPORAH', 41),
 ('TZIPPY', 17),
 ('TZIVIA', 39),
 ('CONNER', 69),
 ('JAMIR', 37),
 ('JALEN', 95),
 ('SHAYLA', 91),
 ('ARIELA', 28),
 ('ANALIA', 75),
 ('AMYA', 26),
 ('ISIAH', 67),
 ('ANTONY', 36),
 ('TYSHAWN', 7),
 ('CONNIE', 33),
 ('ZELDY', 20),
 ('CESIA', 7),
 ('RAUL', 56),
 ('RHEA', 25),
 ('ANGELINE', 36),
 ('FRANCO', 20),
 ('RIVKAH', 49),
 ('EZRIEL', 35),
 ('KRISH', 51),
 ('KYLER', 44),
 ('THERESA', 28),
 ('DAVION', 23),
 ('BENNY', 36),
 ('LEIB', 39),
 ('KAMARI', 69),
 ('CHEYENNE', 64),
 ('YASMIN', 74),
 ('YARIEL', 49),
 ('BRETT', 56),
 ('TINA', 38),
 ('SANIYA', 70),
 ('TRACY', 32),
 ('MARLEY', 117),
 ('JELANI', 23),
 ('AMALIA', 78),
 ('JAZLYN', 84),
 ('JAZLENE', 22),
 ('ELLIS', 57),
 ('AJANI', 21),
 ('BYRON', 43),
 ('ASIA', 20),
 ('JASLENE', 96),
 ('AISSATOU', 31),
 ('ALISSA', 27),
 ('ARYANNA', 42),
 ('ASHANTI', 18),
 ('ASHLEE', 35),
 ('ATARA', 32),
 ('BRAYLON', 14),
 ('BROCHA', 27),
 ('CAROLYN', 39),
 ('CAYLEE', 13),
 ('CLAUDIA', 39),
 ('CURTIS', 40),
 ('DAMANI', 20),
 ('DAMARIS', 22),
 ('DENISE', 87),
 ('DINAH', 7),
 ('ELIANNA', 60),
 ('FILIP', 26),
 ('HEATHER', 53),
 ('JABARI', 26),
 ('JAEDEN', 22),
 ('JAHDIEL', 12),
 ('JANIAH', 32),
 ('KALEIGH', 17),
 ('LANA', 94),
 ('MAHAMADOU', 29),
 ('MENUCHA', 33),
 ('PAMELA', 35),
 ('REBEKAH', 31),
 ('SHELBY', 34),
 ('TAMAR', 38),
 ('TARYN', 18),
 ('TERENCE', 15),
 ('TERESA', 33),
 ('TERRELL', 25),
 ('TREY', 34),
 ('WILMER', 16),
 ('ZACKARY', 38),
 ('TYRESE', 23),
 ('TIARA', 20),
 ('TALYA', 22),
 ('SHAMAR', 16),
 ('SEBASTIEN', 28),
 ('PRECIOUS', 20),
 ('MUSTAFA', 59),
 ('MARINA', 38),
 ('LIZ', 15),
 ('LESLEY', 28),
 ('KATRINA', 30),
 ('JOSELIN', 11),
 ('JEROME', 25),
 ('JERAMIAH', 7),
 ('JAIDA', 41),
 ('JACQUELYN', 11),
 ('JACKLYN', 11),
 ('ISAIAS', 23),
 ('HILLARY', 34),
 ('GISSELLE', 15),
 ('GILLIAN', 11),
 ('GERSHON', 26),
 ('GERALD', 33),
 ('EVELIN', 7),
 ('EMILIE', 34),
 ('DAYANARA', 13),
 ('DARNELL', 22),
 ('CALEIGH', 16),
 ('ANITA', 26),
 ('MOISES', 38),
 ('NAZIR', 24),
 ('KELLEN', 26),
 ('SHANIYA', 16),
 ('LISA', 59),
 ('JAHZARA', 20),
 ('HENCHY', 31),
 ('HAROLD', 26),
 ('ELUZER', 29),
 ('MARIELLA', 20),
 ('KIERSTEN', 10),
 ('ADITYA', 21),
 ('TESS', 31),
 ('JAILYN', 21),
 ('TABITHA', 17),
 ('CARISSA', 16),
 ('JOHANN', 16),
 ('ALANIS', 38),
 ('KHADIJAH', 36),
 ('HAVEN', 32),
 ('ZARIAH', 39),
 ('AYANA', 38),
 ('ANAYAH', 37),
 ('ROYAL', 74),
 ('ALEAH', 37),
 ('LYLAH', 24),
 ('ABRIELLE', 16),
 ('NATHALIA', 32),
 ('KADIATOU', 17),
 ('MAIMOUNA', 13),
 ('NICHOLE', 8),
 ('AWA', 11),
 ('JERELYN', 8),
 ('RAMATOULAYE', 8),
 ('ZAIDEN', 50),
 ('KYRIE', 120),
 ('MAJOR', 46),
 ('ORLANDO', 31),
 ('ABOUBACAR', 22),
 ('ADRIEN', 26),
 ('JOEY', 37),
 ('QUINCY', 45),
 ('DORIAN', 33),
 ('JAYCOB', 24),
 ('ENOCH', 14),
 ('DAVON', 17),
 ('BOUBACAR', 17),
 ('MATTIE', 19),
 ('FINLEY', 94),
 ('ADELYNN', 44),
 ('RYKER', 44),
 ('KNOX', 30),
 ('WILLA', 72),
 ('SAMIRA', 70),
 ('AYESHA', 62),
 ('AYA', 39),
 ('MAISIE', 32),
 ('JUNIPER', 51),
 ('AZIZA', 19),
 ('MINA', 50),
 ('SARIYAH', 26),
 ('ROCHELLE', 13),
 ('ALIA', 46),
 ('FREYA', 50),
 ('NAYA', 37),
 ('AMIA', 37),
 ('SHEILA', 23),
 ('CLEMENTINE', 34),
 ('PALOMA', 29),
 ("CHLOE'", 14),
 ('QUEENA', 21),
 ('SIMI', 16),
 ('BLIMIE', 15),
 ('AVIVA', 47),
 ('SAMIYA', 21),
 ('ROSIE', 27),
 ('HARLOW', 31),
 ('LUCILLE', 45),
 ('KHADIJA', 33),
 ('ZOYA', 27),
 ('DALIA', 39),
 ('RINA', 32),
 ('JOURNEE', 22),
 ('AMAYAH', 32),
 ('AMEERA', 30),
 ('YASMEEN', 17),
 ('PERI', 16),
 ('AIDEL', 13),
 ('REIZEL', 9),
 ('KAMRYN', 46),
 ('DOROTHY', 36),
 ('BLAIR', 35),
 ('KACEY', 18),
 ('EMMELINE', 28),
 ('CLARISSA', 22),
 ('AMINAH', 39),
 ('IVANNA', 17),
 ('SAFA', 28),
 ('SIDNEY', 27),
 ('ZAYNAB', 24),
 ('AGNES', 23),
 ('IRINA', 18),
 ('MARWA', 18),
 ('AMEERAH', 12),
 ('NAVA', 19),
 ('LUCINDA', 13),
 ('OONA', 20),
 ('SABINA', 21),
 ('SUMAYA', 18),
 ('TANYA', 13),
 ('HAREEM', 11),
 ('NATALYA', 21),
 ('SADIA', 11),
 ('HADIYA', 8),
 ('HENNA', 12),
 ('PENINA', 8),
 ('TALA', 18),
 ('VENUS', 10),
 ('BLUMA', 12),
 ('FELICIA', 13),
 ('SHELLY', 9),
 ('KAMAYA', 7),
 ('SHEINA', 11),
 ('UNA', 12),
 ('TZIVI', 7),
 ('KIMI', 47),
 ('ZAHIR', 25),
 ('AAHIL', 33),
 ('NOAM', 55),
 ('YIDEL', 25),
 ('RHYS', 54),
 ('LEGEND', 45),
 ('TYSON', 35),
 ('LEV', 42),
 ('CASSIUS', 30),
 ('ABE', 16),
 ('ZAMIR', 18),
 ('SHAUL', 17),
 ('YONAH', 22),
 ('YONASON', 10),
 ('GIDEON', 38),
 ('ROBIN', 33),
 ('NATHANAEL', 33),
 ('NIKOLAI', 37),
 ('SAVION', 11),
 ('ASA', 27),
 ('IMRAN', 29),
 ('YONATAN', 21),
 ('STEPHAN', 25),
 ('BINYAMIN', 20),
 ('ZALMAN', 12),
 ('LEIBY', 15),
 ('MALEK', 16),
 ('ELIE', 14),
 ('BURECH', 13),
 ('NESANEL', 15),
 ('TRISTEN', 30),
 ('EDDY', 18),
 ('MAISON', 38),
 ('KARIM', 16),
 ('JAMAR', 21),
 ('ARVIN', 19),
 ('AZAAN', 23),
 ('MOISHY', 13),
 ('SHLOIMA', 10),
 ('SHLOMIE', 8),
 ('NOACH', 19),
 ('AZIM', 7),
 ('CHANANYA', 9),
 ('KIAN', 55),
 ('ZAYAN', 32),
 ('AUGUSTUS', 30),
 ('LEWIS', 38),
 ('SAMSON', 23),
 ('ANAS', 26),
 ('BOWEN', 25),
 ('AZARIAH', 35),
 ('DIMITRI', 28),
 ('SHLOMA', 36),
 ('ADHAM', 11),
 ('DAVE', 21),
 ('RAY', 25),
 ('TRISTIAN', 26),
 ('RAHEEM', 18),
 ('MOHAMAD', 9),
 ('MIKHAIL', 20),
 ('ABDULRAHMAN', 14),
 ('BENYAMIN', 11),
 ('FEYNMAN', 19),
 ('MOTTY', 11),
 ('ASADBEK', 12),
 ('BEHRUZ', 9),
 ('MESHULEM', 15),
 ('SHOHJAHON', 9),
 ('DOVBER', 8),
 ('TEMUR', 8)]

Now `map` the name,frequency pairs so that you only have the values and use the `max` action to get the highest value.

In [38]:
maxname = kv.max(lambda x: int(x[1]))
maxname

('MICHAEL', 12749)

And revert back to the name,frequency pairs and filter the pair(s) that have a frequency equal to the max you found.

### No reason to map to a single value and then filter to match the value to a tuple when the max function can accept a lambda to look at the second value of the tuple
Also, that's just more susceptible to errors.

### Also, the original 'correct' answer didn't actually aggregate the count so it just looked at which name was present in the most counties rather than which name actually was most present.